# Generated by Django 2.0.2 on 2018-02-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limit_val',
            options={'verbose_name_plural': 'Резервы валюты'},
        ),
    ]
