# Generated by Django 2.0.2 on 2018-02-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_limit_val_min_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit_val',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
