# Generated by Django 2.0.2 on 2018-02-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180218_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit_val',
            name='min_val',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='limit_val',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
