# Generated by Django 2.0.2 on 2018-03-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180221_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterField(
            model_name='limit_val',
            name='index',
            field=models.CharField(max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='limit_val',
            name='min_val',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Мин знач'),
        ),
        migrations.AlterField(
            model_name='limit_val',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='limit_val',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Резерв'),
        ),
    ]
