# Generated by Django 2.0.2 on 2018-03-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180301_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='limit_val',
            new_name='LimitVal',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
