# Generated by Django 2.0.2 on 2018-03-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('card_number', models.CharField(max_length=20, verbose_name='Номер карты')),
                ('input_val', models.CharField(max_length=20, verbose_name='Валюта приема')),
                ('output_val', models.CharField(max_length=20, verbose_name='Валюта отдачи')),
                ('sum_from', models.CharField(max_length=10, verbose_name='Сумма приема')),
                ('sum_to', models.CharField(max_length=10, verbose_name='Сумма отдачи')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
